name: release

jobs:
  build:
    strategy:
      matrix:
        java: [
          21,
        ]
    runs-on: ubuntu-22.04
    outputs:
      mod-version: ${{ steps.grab_version.outputs.mod-version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: grab mod version
        id: grab_version
        run: ./gradlew -q :logVersion >> "$GITHUB_OUTPUT"
      - name: print version
        run: echo "${{ steps.grab_version.outputs.mod-version }}"
